FROM amazoncorretto:17.0.7
LABEL authors="ybyoon"

WORKDIR /var/lib/jenkins/workspace

ARG JAR_PATH=./build/libs

COPY ${JAR_PATH}/api-0.0.1-SNAPSHOT.jar ${JAR_PATH}/api-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","./build/libs/api-0.0.1-SNAPSHOT.jar"]


#ENTRYPOINT ["top", "-b"]